// Generated by: gen
// TypeWriter: slice
// Directive: +gen on Group

package master

// GroupSlice is a slice of type Group. Use it where you would use []Group.
type GroupSlice []Group

// Where returns a new GroupSlice whose elements return true for func. See: http://clipperhouse.github.io/gen/#Where
func (rcv GroupSlice) Where(fn func(Group) bool) (result GroupSlice) {
	for _, v := range rcv {
		if fn(v) {
			result = append(result, v)
		}
	}
	return result
}

// GroupByInt groups elements into a map keyed by int. See: http://clipperhouse.github.io/gen/#GroupBy
func (rcv GroupSlice) GroupByInt(fn func(Group) int) map[int]GroupSlice {
	result := make(map[int]GroupSlice)
	for _, v := range rcv {
		key := fn(v)
		result[key] = append(result[key], v)
	}
	return result
}

// Any verifies that one or more elements of GroupSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#Any
func (rcv GroupSlice) Any(fn func(Group) bool) bool {
	for _, v := range rcv {
		if fn(v) {
			return true
		}
	}
	return false
}
